// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCojYxN7jIo3QYT3Wa290I80RI0yUBj8P0',
    appId: '1:70272764878:web:03b204c2feb809a95db99f',
    messagingSenderId: '70272764878',
    projectId: 'what-s-app-7bd47',
    authDomain: 'what-s-app-7bd47.firebaseapp.com',
    storageBucket: 'what-s-app-7bd47.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGDEZY6R2Wqist3GU9mtoST5qf4-eLUyI',
    appId: '1:70272764878:android:5f5e77579a5a44a95db99f',
    messagingSenderId: '70272764878',
    projectId: 'what-s-app-7bd47',
    storageBucket: 'what-s-app-7bd47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHsVBgjBMzvjBRLsMx_kmPNA8J1MNYLU',
    appId: '1:70272764878:ios:fd6428520a6cf3525db99f',
    messagingSenderId: '70272764878',
    projectId: 'what-s-app-7bd47',
    storageBucket: 'what-s-app-7bd47.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrHsVBgjBMzvjBRLsMx_kmPNA8J1MNYLU',
    appId: '1:70272764878:ios:fd6428520a6cf3525db99f',
    messagingSenderId: '70272764878',
    projectId: 'what-s-app-7bd47',
    storageBucket: 'what-s-app-7bd47.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCojYxN7jIo3QYT3Wa290I80RI0yUBj8P0',
    appId: '1:70272764878:web:2a8c2f0895a6c1895db99f',
    messagingSenderId: '70272764878',
    projectId: 'what-s-app-7bd47',
    authDomain: 'what-s-app-7bd47.firebaseapp.com',
    storageBucket: 'what-s-app-7bd47.firebasestorage.app',
  );

}